name: 🔱 AKAME OMEGA FORGE
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout (Native 2026)
        uses: actions/checkout@v4.1.2 # Versão otimizada

      - name: ☕ Java 21 (Temurin Distribution)
        uses: actions/setup-java@v4.2.1 # Versão otimizada para Node 24
        with:
          java-version: "17"
          distribution: 'temurin'
          cache: 'gradle'

      - name: 🛠️ Permissões de Execução
        run: chmod +x gradlew

      - name: 🚀 Build Total (Modo Inabalável)
        # O flag --no-daemon garante que o processo não fique pendurado
        run: ./gradlew assembleDebug --no-daemon --stacktrace -Dorg.gradle.jvmargs=-Xmx2048m
