name: 🔱 AKAME APP FORGE

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: 📥 Clonar Ecossistema
        uses: actions/checkout@v4

      - name: ☕ Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 🛡️ Conceder Permissão Total ao Motor
        run: |
          chmod +x app/gradlew
          chmod +x gradlew

      - name: 🔨 Forjar APK (Alvo Direto)
        run: |
          cd app
          /bin/bash ./gradlew assembleDebug --stacktrace

      - name: 📦 Disponibilizar Artefato
        uses: actions/upload-artifact@v4
        with:
          name: AkameNexus-Debug
          path: app/app/build/outputs/apk/debug/*.apk
