name: Forja de Video Akame S-Rank
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Codigo
        uses: actions/checkout@v4

      - name: Configurar FFmpeg (Motor de Video)
        run: sudo apt-get install ffmpeg -y

      - name: Processamento de Alta Performance
        run: |
          # Aqui o GitHub une os frames em um video de alta qualidade
          # -framerate 30 (Velocidade) -crf 18 (Qualidade Cinema)
          ffmpeg -framerate 30 -pattern_type glob -i '*.jpg' -c:v libx264 -pix_fmt yuv420p video_final.mp4

      - name: Gerar Artefato (O Video para Download)
        uses: actions/upload-artifact@v4
        with:
          name: video_final
          path: video_final.mp4
